In [1]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (1.5.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: scipy>=1.6.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.26.4)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install spacy

Collecting spacy
  Using cached spacy-3.7.6-cp310-cp310-win_amd64.whl (12.1 MB)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4
  Using cached pydantic-2.9.2-py3-none-any.whl (434 kB)
Collecting preshed<3.1.0,>=3.0.2
  Using cached preshed-3.0.9-cp310-cp310-win_amd64.whl (122 kB)
Requirement already satisfied: setuptools in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy) (63.2.0)
Collecting srsly<3.0.0,>=2.4.3
  Using cached srsly-2.4.8-cp310-cp310-win_amd64.whl (481 kB)
Collecting langcodes<4.0.0,>=3.2.0
  Using cached langcodes-3.4.0-py3-none-any.whl (182 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: numpy>=1.19.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy) (1.26.4)
Collecting thinc<8.3.0,>=8.2.2
  Using cached thinc-8.2.5-cp310-cp310-win_amd64.whl (1.5 MB)
Collecting murmurhash<1.1.0,>=0.28.0
  Using cached murmurhash-1.0.10-cp310-cp310-win_amd64.whl (25 kB)
Requirement already satisfied: jinja2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy) (3.1.4)
Collecting typer<1.0.0,>=0.3.0
  Using cached typer-0.12.5-py3-none-any.whl (47 kB)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: packaging>=20.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy) (24.1)
Collecting catalogue<2.1.0,>=2.0.6
  Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy) (2.32.3)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy) (2.0.8)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy) (1.1.3)
Collecting weasel<0.5.0,>=0.1.0
  Using cached weasel-0.4.1-py3-none-any.whl (50 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy) (4.66.5)
Collecting language-data>=1.2
  Using cached language_data-1.2.0-py3-none-any.whl (5.4 MB)
Requirement already satisfied: pydantic-core==2.23.4 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.23.4)
Collecting annotated-types>=0.6.0
  Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.6.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.2.2)
Collecting confection<1.0.0,>=0.0.1
  Using cached confection-0.1.5-py3-none-any.whl (35 kB)
Collecting blis<0.8.0,>=0.7.8
  Using cached blis-0.7.11-cp310-cp310-win_amd64.whl (6.6 MB)
Requirement already satisfied: colorama in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Collecting rich>=10.11.0
  Using cached rich-13.8.1-py3-none-any.whl (241 kB)
Requirement already satisfied: click>=8.0.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.7)
Collecting cloudpathlib<1.0.0,>=0.7.0
  Using cached cloudpathlib-0.19.0-py3-none-any.whl (49 kB)
Collecting smart-open<8.0.0,>=5.2.1
  Using cached smart_open-7.0.4-py3-none-any.whl (61 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from jinja2->spacy) (2.1.5)
Collecting marisa-trie>=0.7.7
  Using cached marisa_trie-1.2.0-cp310-cp310-win_amd64.whl (152 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.18.0)
Collecting markdown-it-py>=2.2.0
  Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Requirement already satisfied: wrapt in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (1.16.0)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: smart-open, murmurhash, mdurl, marisa-trie, cloudpathlib, catalogue, blis, annotated-types, srsly, pydantic, preshed, markdown-it-py, language-data, rich, langcodes, confection, typer, thinc, weasel, spacy
Successfully installed annotated-types-0.7.0 blis-0.7.11 catalogue-2.0.10 cloudpathlib-0.19.0 confection-0.1.5 langcodes-3.4.0 language-data-1.2.0 marisa-trie-1.2.0 markdown-it-py-3.0.0 mdurl-0.1.2 murmurhash-1.0.10 preshed-3.0.9 pydantic-2.9.2 rich-13.8.1 smart-open-7.0.4 spacy-3.7.6 srsly-2.4.8 thinc-8.2.5 typer-0.12.5 weasel-0.4.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
!python -m spacy download en_core_web_lg

Collecting en-core-web-lg==3.7.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.7.1/en_core_web_lg-3.7.1-py3-none-any.whl (587.7 MB)
     -------------------------------------- 587.7/587.7 MB 1.3 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from en-core-web-lg==3.7.1) (3.7.6)
Requirement already satisfied: jinja2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.1.4)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (8.2.5)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.0.10)
Requirement already satisfied: numpy>=1.19.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.32.3)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.0.5)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.4.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.0.8)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.12.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.9.2)
Requirement already satisfied: setuptools in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (63.2.0)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.0.9)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.0.10)
Requirement already satisfied: packaging>=20.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (24.1)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.1.3)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.4.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (4.66.5)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.4.8)
Requirement already satisfied: language-data>=1.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.2.0)
Requirement already satisfied: pydantic-core==2.23.4 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.23.4)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.7.0)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (4.12.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2024.6.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.3.2)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.1.5)
Requirement already satisfied: colorama in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.4.6)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.5.4)
Requirement already satisfied: click>=8.0.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (8.1.7)
Requirement already satisfied: rich>=10.11.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (13.8.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.19.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (7.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.1.5)
Requirement already satisfied: marisa-trie>=0.7.7 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.18.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.0.0)
Requirement already satisfied: wrapt in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.16.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.1.2)
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-3.7.1
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')

[notice] A new release of pip available: 22.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report


from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

import spacy
nlp = spacy.load("en_core_web_lg")

import warnings
warnings.filterwarnings('ignore')

In [2]:
col = ['Date','News']
data = pd.read_csv(r"C:\Users\Administrator\a751809\Fid-Case-Study\sentiment_analysis\RedditNews.csv", names=col)

In [3]:
data.head()

         Date                                               News
0        Date                                               News
1  2016-07-01  A 117-year-old woman in Mexico City finally re...
2  2016-07-01   IMF chief backs Athens as permanent Olympic host
3  2016-07-01  The president of France says if Brexit won, so...
4  2016-07-01  British Man Who Must Give Police 24 Hours' Not...

In [4]:
data.shape

(73609, 2)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73609 entries, 0 to 73608
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    73609 non-null  object
 1   News    73609 non-null  object
dtypes: object(2)
memory usage: 1.1+ MB

In [6]:
data.dropna(inplace=True)

In [19]:
nlp = spacy.load("en_core_web_lg") 
def preprocess(text):
    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)
    #print("preprocess successful")
    return " ".join(filtered_tokens)

In [20]:
result = preprocess("Hello, you are a bad guy?? why are you not working on your grades!!!!")
print(result)

hello bad guy work grade

In [28]:
import time

In [30]:
start_time = time.time()
print(start_time)
data['Preprocessed Text'] = data['News'].apply(preprocess) 
end_time = time.time()
total_time_taken = end_time - start_time
print(total_time_taken)

1727240232.3518138
1483.2724742889404

In [31]:
data

,Date,News,Preprocessed Text
0,Date,News,news
1,2016-07-01,A 117-year-old woman in Mexico City finally re...,117 year old woman Mexico City finally receive...
2,2016-07-01,IMF chief backs Athens as permanent Olympic host,IMF chief back Athens permanent olympic host
3,2016-07-01,"The president of France says if Brexit won, so...",president France say Brexit win Donald Trump
4,2016-07-01,British Man Who Must Give Police 24 Hours' Not...,british Man Police 24 hour notice sex threaten...
...,...,...,...
73604,2008-06-08,b'Man goes berzerk in Akihabara and stabs ever...,b'man go berzerk Akihabara stab nearby 6 dead ...
73605,2008-06-08,b'Threat of world AIDS pandemic among heterose...,b'threat world AIDS pandemic heterosexual repo...
73606,2008-06-08,b'Angst in Ankara: Turkey Steers into a Danger...,b'Angst Ankara Turkey Steers dangerous Identit...
73607,2008-06-08,"b""UK: Identity cards 'could be used to spy on ...","b""UK identity card spy people new child databa..."
73608,2008-06-08,"b'Marriage, they said, was reduced to the stat...",b'Marriage say reduce status commercial transa...

In [32]:
try:
    data.to_csv(r"C:\Users\Administrator\a751809\Fid-Case-Study\sentiment_analysis\RedditNews_preprocessed.csv", index = True)
    print(f"File saved")
except:
    print(f"File saving failed")

File saved

In [33]:
try:
    data.to_csv(r"C:\Users\Administrator\a751809\Fid-Case-Study\sentiment_analysis\News_data.csv")
    print("File saved!")
except:
    print("Saving final data failed")

File saved!

In [34]:
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [35]:
def get_score_nltk(text):
    nltk.download('vader_lexicon',quiet=True)
    sia = SentimentIntensityAnalyzer()
    sentiment_score = sia.polarity_scores(text)
    return sentiment_score["compound"]

In [36]:
data['Sentiment_score'] = data['Preprocessed Text'].apply(get_score_nltk)

In [37]:
data

,Date,News,Preprocessed Text,Sentiment_score
0,Date,News,news,0.0000
1,2016-07-01,A 117-year-old woman in Mexico City finally re...,117 year old woman Mexico City finally receive...,-0.5994
2,2016-07-01,IMF chief backs Athens as permanent Olympic host,IMF chief back Athens permanent olympic host,0.0000
3,2016-07-01,"The president of France says if Brexit won, so...",president France say Brexit win Donald Trump,0.5859
4,2016-07-01,British Man Who Must Give Police 24 Hours' Not...,british Man Police 24 hour notice sex threaten...,-0.5187
...,...,...,...,...
73604,2008-06-08,b'Man goes berzerk in Akihabara and stabs ever...,b'man go berzerk Akihabara stab nearby 6 dead ...,-0.8442
73605,2008-06-08,b'Threat of world AIDS pandemic among heterose...,b'threat world AIDS pandemic heterosexual repo...,0.2023
73606,2008-06-08,b'Angst in Ankara: Turkey Steers into a Danger...,b'Angst Ankara Turkey Steers dangerous Identit...,-0.8020
73607,2008-06-08,"b""UK: Identity cards 'could be used to spy on ...","b""UK identity card spy people new child databa...",-0.5267
73608,2008-06-08,"b'Marriage, they said, was reduced to the stat...",b'Marriage say reduce status commercial transa...,-0.5267

In [38]:
try:
    data.to_csv(r"C:\Users\Administrator\a751809\Fid-Case-Study\sentiment_analysis\News_data.csv")
    print("File saved!")
except:
    print("Saving final data failed")

File saved!